create table trip_detail
(
    id         bigint generated by default as identity,
    client_id  bigint not null,
    driver_id  bigint not null,
    region_id  bigint not null,
    request_at date,
    status     varchar(255),
    user_id    bigint,
    primary key (id)
);

